// Sample foods from USDA FoodData Central for development and testing.
// In production, a full import script will pull from the USDA API.

import type { InferInsertModel } from "drizzle-orm";
import type { foods } from "../schema";

type NewFood = InferInsertModel<typeof foods>;

export const sampleFoods: NewFood[] = [
  // ── Proteins ──────────────────────────────────────────────
  {
    name: "Chicken Breast, boneless, skinless, cooked",
    source: "usda",
    sourceId: "171077",
    servingSizeG: "140",
    servingLabel: "1 breast (140g)",
    calories: "231",
    proteinG: "43.40",
    carbsG: "0.00",
    fatG: "5.04",
    fiberG: "0.00",
    sugarG: "0.00",
    sodiumMg: "104.0",
    category: "protein",
    tags: ["high_protein", "whole_food", "quick"],
    isVerified: true,
  },
  {
    name: "Salmon, Atlantic, cooked",
    source: "usda",
    sourceId: "175168",
    servingSizeG: "170",
    servingLabel: "1 fillet (170g)",
    calories: "367",
    proteinG: "39.30",
    carbsG: "0.00",
    fatG: "22.10",
    fiberG: "0.00",
    sugarG: "0.00",
    sodiumMg: "109.0",
    category: "protein",
    tags: ["high_protein", "whole_food"],
    isVerified: true,
  },
  {
    name: "Eggs, whole, scrambled",
    source: "usda",
    sourceId: "171287",
    servingSizeG: "91",
    servingLabel: "2 large eggs",
    calories: "182",
    proteinG: "12.10",
    carbsG: "2.00",
    fatG: "13.80",
    fiberG: "0.00",
    sugarG: "1.60",
    sodiumMg: "342.0",
    category: "protein",
    tags: ["quick", "whole_food"],
    isVerified: true,
  },
  {
    name: "Greek Yogurt, plain, nonfat",
    source: "usda",
    sourceId: "170903",
    servingSizeG: "245",
    servingLabel: "1 cup (245g)",
    calories: "133",
    proteinG: "23.00",
    carbsG: "7.35",
    fatG: "0.73",
    fiberG: "0.00",
    sugarG: "7.35",
    sodiumMg: "82.0",
    category: "dairy",
    tags: ["high_protein", "quick", "whole_food"],
    isVerified: true,
  },
  {
    name: "Ground Turkey, 93% lean, cooked",
    source: "usda",
    sourceId: "171488",
    servingSizeG: "112",
    servingLabel: "4 oz (112g)",
    calories: "190",
    proteinG: "22.30",
    carbsG: "0.00",
    fatG: "10.70",
    fiberG: "0.00",
    sugarG: "0.00",
    sodiumMg: "88.0",
    category: "protein",
    tags: ["high_protein", "whole_food"],
    isVerified: true,
  },

  // ── Grains & Carbs ───────────────────────────────────────
  {
    name: "Oatmeal, cooked, plain",
    source: "usda",
    sourceId: "173904",
    servingSizeG: "234",
    servingLabel: "1 cup cooked (234g)",
    calories: "154",
    proteinG: "5.40",
    carbsG: "27.40",
    fatG: "2.60",
    fiberG: "4.00",
    sugarG: "0.60",
    sodiumMg: "115.0",
    category: "grain",
    tags: ["whole_food", "quick"],
    isVerified: true,
  },
  {
    name: "Brown Rice, cooked",
    source: "usda",
    sourceId: "169704",
    servingSizeG: "195",
    servingLabel: "1 cup cooked (195g)",
    calories: "216",
    proteinG: "4.50",
    carbsG: "44.80",
    fatG: "1.80",
    fiberG: "3.50",
    sugarG: "0.70",
    sodiumMg: "10.0",
    category: "grain",
    tags: ["whole_food"],
    isVerified: true,
  },
  {
    name: "Sweet Potato, baked",
    source: "usda",
    sourceId: "168482",
    servingSizeG: "114",
    servingLabel: "1 medium (114g)",
    calories: "103",
    proteinG: "2.30",
    carbsG: "23.60",
    fatG: "0.11",
    fiberG: "3.80",
    sugarG: "7.40",
    sodiumMg: "41.0",
    category: "vegetable",
    tags: ["whole_food"],
    isVerified: true,
  },
  {
    name: "Whole Wheat Bread",
    source: "usda",
    sourceId: "168012",
    servingSizeG: "43",
    servingLabel: "1 slice (43g)",
    calories: "110",
    proteinG: "5.00",
    carbsG: "19.00",
    fatG: "1.80",
    fiberG: "2.70",
    sugarG: "2.60",
    sodiumMg: "200.0",
    category: "grain",
    tags: ["whole_food", "quick"],
    isVerified: true,
  },
  {
    name: "Banana, medium",
    source: "usda",
    sourceId: "173944",
    servingSizeG: "118",
    servingLabel: "1 medium (118g)",
    calories: "105",
    proteinG: "1.30",
    carbsG: "27.00",
    fatG: "0.39",
    fiberG: "3.10",
    sugarG: "14.40",
    sodiumMg: "1.0",
    category: "fruit",
    tags: ["whole_food", "quick"],
    isVerified: true,
  },

  // ── Vegetables ────────────────────────────────────────────
  {
    name: "Broccoli, cooked",
    source: "usda",
    sourceId: "170379",
    servingSizeG: "156",
    servingLabel: "1 cup chopped (156g)",
    calories: "55",
    proteinG: "3.70",
    carbsG: "11.20",
    fatG: "0.64",
    fiberG: "5.10",
    sugarG: "2.20",
    sodiumMg: "64.0",
    category: "vegetable",
    tags: ["whole_food", "low_carb"],
    isVerified: true,
  },
  {
    name: "Spinach, raw",
    source: "usda",
    sourceId: "168462",
    servingSizeG: "30",
    servingLabel: "1 cup (30g)",
    calories: "7",
    proteinG: "0.86",
    carbsG: "1.09",
    fatG: "0.12",
    fiberG: "0.70",
    sugarG: "0.13",
    sodiumMg: "24.0",
    category: "vegetable",
    tags: ["whole_food", "low_carb", "quick"],
    isVerified: true,
  },

  // ── Fats & Nuts ───────────────────────────────────────────
  {
    name: "Almonds, raw",
    source: "usda",
    sourceId: "170567",
    servingSizeG: "28",
    servingLabel: "1 oz (28g)",
    calories: "164",
    proteinG: "6.00",
    carbsG: "6.10",
    fatG: "14.20",
    fiberG: "3.50",
    sugarG: "1.20",
    sodiumMg: "0.0",
    category: "nut",
    tags: ["whole_food", "quick"],
    isVerified: true,
  },
  {
    name: "Avocado, raw",
    source: "usda",
    sourceId: "171706",
    servingSizeG: "150",
    servingLabel: "1 medium (150g)",
    calories: "240",
    proteinG: "3.00",
    carbsG: "12.80",
    fatG: "22.00",
    fiberG: "10.00",
    sugarG: "1.00",
    sodiumMg: "11.0",
    category: "fruit",
    tags: ["whole_food"],
    isVerified: true,
  },
  {
    name: "Olive Oil, extra virgin",
    source: "usda",
    sourceId: "171413",
    servingSizeG: "14",
    servingLabel: "1 tbsp (14g)",
    calories: "119",
    proteinG: "0.00",
    carbsG: "0.00",
    fatG: "13.50",
    fiberG: "0.00",
    sugarG: "0.00",
    sodiumMg: "0.0",
    category: "fat",
    tags: ["whole_food", "quick"],
    isVerified: true,
  },

  // ── Common Branded (Open Food Facts placeholders) ─────────
  {
    name: "Quest Protein Bar, Chocolate Chip Cookie Dough",
    brand: "Quest Nutrition",
    barcode: "888849000036",
    source: "off",
    servingSizeG: "60",
    servingLabel: "1 bar (60g)",
    calories: "200",
    proteinG: "21.00",
    carbsG: "22.00",
    fatG: "8.00",
    fiberG: "14.00",
    sugarG: "1.00",
    sodiumMg: "300.0",
    category: "snack",
    tags: ["high_protein", "quick"],
    isVerified: false,
  },
  {
    name: "Chobani Greek Yogurt, Vanilla, Nonfat",
    brand: "Chobani",
    barcode: "818290010001",
    source: "off",
    servingSizeG: "150",
    servingLabel: "1 container (150g)",
    calories: "120",
    proteinG: "15.00",
    carbsG: "15.00",
    fatG: "0.00",
    fiberG: "0.00",
    sugarG: "12.00",
    sodiumMg: "55.0",
    category: "dairy",
    tags: ["high_protein", "quick"],
    isVerified: false,
  },
  {
    name: "Fairlife Milk, 2% Reduced Fat, Ultra-Filtered",
    brand: "Fairlife",
    barcode: "811620020010",
    source: "off",
    servingSizeG: "240",
    servingLabel: "1 cup (240ml)",
    calories: "120",
    proteinG: "13.00",
    carbsG: "6.00",
    fatG: "4.50",
    fiberG: "0.00",
    sugarG: "6.00",
    sodiumMg: "150.0",
    category: "dairy",
    tags: ["high_protein", "quick"],
    isVerified: false,
  },
];
